Q1. How is total revenue distributed across behavioral retention segments?
select behavioral_segment, 
count(customer_id) as total_customers, 
sum(purchase_amount) as total_revenue
from customer
group by behavioral_segment
order by total_revenue desc;


Q2. What percentage of total revenue is currently dependent on churn-risk customers?
select revenue_risk_flag, 
round(sum(purchase_amount) * 100.0 / (select sum(purchase_amount) from customer), 2) as revenue_per
from customer 
group by revenue_risk_flag;


Q3. Do subscribed customers demonstrate stronger behavioral retention than non-subscribers?
select subscription_status, 
round(avg(retention_score)::numeric,2) AS avg_retention_score, 
sum(purchase_amount) as total_revenue 
from customer
group by subscription_status;


Q4. Which product categories contribute the most revenue from churn-risk customers?
select category, 
behavioral_segment, 
sum(purchase_amount) as total_revenue
from customer
where behavioral_segment IN ('High Churn Risk', 'Moderate Risk')
group by category, behavioral_segment
order by total_revenue desc;


Q5. Who are the top 10 high-value customers currently at high churn risk?
select customer_id, 
purchase_amount, 
previous_purchases,
(purchase_amount * previous_purchases) as estimated_clv, 
round(retention_score::numeric, 2) as retention_score
from customer 
where behavioral_segment like 'High Churn Risk'
and purchase_amount > (select avg(purchase_amount) from customer)
order by estimated_clv desc
limit 10;


Q6. What is the total revenue generated by moderately engaged customers (preventable churn pool)?
select sum(purchase_amount) as moderate_risk_revenue 
from customer
where behavioral_segment like 'Moderate Risk';


Q7. Which product categories have the highest concentration of high churn-risk customers? 
select category, 
count(customer_id) as high_risk_customers
from customer 
where behavioral_segment like 'High Churn Risk'
group by category 
order by high_risk_customers desc;


Q8. What are the top 3 most purchased products within each category?
with ranked_products as
(select category, 
item_purchased, 
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as rnk
from customer
group by category, item_purchased)

select category, item_purchased, total_orders
from ranked_products
where rnk <=3;


Q9. Which 5 products have the highest percentage of discounted purchases?
select item_purchased, round(100.0 * sum
(case when discount_applied like 'Yes' then 1 
else 0 
end)/count(*),2) as discount_rate 
from customer
group by item_purchased
order by discount_rate desc
limit 5;






















